# docker/docker-compose.yml
version: "3.8"
services:
  yii2:
    image: saifuddin337/yii2-app:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
