name: Deploy Yii2 App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/yii2-app:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{secrets.DOCKER_USERNAME}}/yii2-app:latest
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull secrets.DOCKER_USERNAME/yii2-app:latest
            docker stack deploy -c /home/ubuntu/Basicbankingsystem/docker-compose.yml yii2stack
